### ISSUE TITLE
Problema na documentação

### ISSUE THREAD

**Issue by leonardoquevedox** [wirecardBrasil/moip-encryption-js-jquery#16]
Olá!

Antes de mais nada, parabéns pelo SDK: ele é incrível!

Apenas para avisar, existem alguns trechos quebrados no seguinte código de exemplo:

'Moip.Validator.cardType("5105105105105100");    //return [Object]MASTERCARD
Moip.Validator.cardType("4111111111111111");    //return [Object]VISA
Moip.Validator.cardType("341111111111111");     //return [Object]AMEX
**moip**.Validator.cardType("30569309025904");      //return [Object]DINERS
Moip.Validator.cardType("3841001111222233334"); //return [Object]HIPERCARD
Moip.**Valditor**.cardType("4514160123456789");    //return [Object]ELO
Moip.**Valditor**.cardType("6370950000000005");    //return [Object]HIPER
Moip.Validator.cardType("9191919191919191");    //return [Object]null'

O correto seria:

`Moip.Validator.cardType("5105105105105100"); //return [Object]MASTERCARD
     Moip.Validator.cardType("4111111111111111"); //return [Object]VISA
     Moip.Validator.cardType("341111111111111"); //return [Object]AMEX
     Moip.Validator.cardType("30569309025904"); //return [Object]DINERS
     Moip.Validator.cardType("3841001111222233334"); //return [Object]HIPERCARD
     Moip.Validator.cardType("4514160123456789"); //return [Object]ELO
     Moip.Validator.cardType("6370950000000005"); //return [Object]HIPER
     Moip.Validator.cardType("9191919191919191"); //return [Object]null`

Novamente, parabéns pelo ótimo trabalho!

**Comment by caioincau** [comment]
Fixed at: https://github.com/moip/moip-sdk-js/commit/8cdb0349cddf1533f9688410bff4d6c26886f149
