### ISSUE TITLE
SDK não valida cartões hipercard que começam com 38

### ISSUE THREAD

**Issue by menezes-** [wirecardBrasil/moip-encryption-js-jquery#25]
Comecei o processo de homologação com o pessoal do Moip e me retornaram que
o meu formulário dava erro ao validar cartões do hipercard. Ao pedir que números de cartão foram usando no teste, me passaram o seguinte: 6062825624254001 e 3841001111222233334.
O primeiro número passa certinho, o segundo é retornando como inválido (apesar de ser válido).
Este problema é confirmado ao olhar no código: https://github.com/moip/moip-sdk-js/blob/master/src/validator.js#L32 

De acordo com [esse](https://gist.github.com/erikhenrique/5931368) gist o certo seria `/^3841[046]0|^60/`
e a validação: `/^(38[0-9]{17}|60[0-9]{14})$/`

Para reproduzir o erro:

``` javascript
Moip.Validator.isValid('3841001111222233334')
```

**Comment by brunolemos** [comment]
Dica geral: Você pode colocar o nome de um repositório no `packages.json`. 
Nesse caso, `moip/moip-sdk-js`.

**Comment by caioincau** [comment]
arrumado em: https://github.com/moip/moip-sdk-js/commit/084c7b01c61f347820a56cfd331dc17d0b285904
