### ISSUE TITLE
Support for hybrid frameworks (RN, Ionic, etc)

### ISSUE THREAD

**Issue by sibelius** [wirecardBrasil/moip-encryption-js-jquery#30]
Does Moip has support to React Native?

any plans for that?

**Comment by ssscassio** [comment]
Any news?

**Comment by thebylito** [comment]
+1

**Comment by russiann** [comment]
+1

**Comment by joaolucasl** [comment]
Oi pessoal! Vamos verificar assim que possível se esse projeto funciona com React Native e Ionic (#31)  e, se não, adicionar suporte.
Agora o Moip tem um time para cuidar das SDKs, mas estamos em número reduzido ainda. Peço desculpas pela demora e um pouquinho de paciência!

Obrigado :)

**Comment by thebylito** [comment]
ótimo, se tiver será o primeiro a oferecer suporte, garanto que será muito bem vindo por nós devs

**Comment by pocesar** [comment]
faz um bump pra v3, pára de usar globals e usar `window`, e faz o export do `Moip` como um module com o browserify, já dá pra usar sem problemas, são as 3 únicas coisas que impedem de usar no momento

**Comment by joaolucasl** [comment]
Pessoal, algum de vcs pode fornecer um use cases em que não funciona pra testarmos em cima? Fizemos alguns testes aqui e funcionou, talvez estejamos em contextos diferentes.

O time está analisando fazermos rewrite da biblioteca com ferramentas mais modernas e já com suporte day-0 pra React e Ionic, mas queremos ver se conseguimos atualizar a atual enquanto isso para resolver o problema de vcs.

Se o snippet for muito grande, pode jogar no Gist ou mandar por email pra `joao[ponto]lucchetta[arroba]moip.com.br`

Abs!

**Comment by brunoosilva** [comment]
Pessoal criei essa versão para Nodejs, talvez ajude. Infelizmente essa versão atual está usando **window/navigator/etc**... coisas que não rola no Node, basicamente é o mesmo código e testes.

https://www.npmjs.com/package/moip-sdk-js

**Comment by presende** [comment]
Pessoal, boa tarde, alguém obteve sucesso na implementação com React Native? Tentei algumas coisas mas já fiquei sem opções. Obrigado!

**Comment by pocesar** [comment]
o jeito é usar a versão do @brunoosilva @presende o pessoal do moip é lento quase parando quando o assunto é dev (já passei poucas e boas com eles)

**Comment by LucasRealMp** [comment]
Boa tarde. 
Alguma novidade sobre o suporte para Ionic 1?

**Comment by zdsantos** [comment]
E ai, pessoal? Já tem alguma novidade em relação ao suporte para Ionic 3?

**Comment by somentelucas** [comment]
Pessoal, demorou mas deu certo! ❤️

Nós oficializamos o repositório que o @brunoosilva desenvolveu e agora ela é nossa SDK oficial de criptografia JS: https://github.com/moip/moip-sdk-js

Essa SDK é compatível com web, ionic (1, 2 e 3), react-native e node. 🎉 

Grande agradecimento à sua contribuição, @brunoosilva
