### ISSUE TITLE
Fazer o publish no npm

### ISSUE THREAD

**Issue by pocesar** [wirecardBrasil/moip-encryption-js-jquery#4]
Atualmente o package [moip](https://www.npmjs.com/package/moip) aponta para um repo que não existe. Vejam se não é melhor usar um namespace (por exemplo @moip/moip-sdk-js, igual eu fiz aqui [moip2](https://www.npmjs.com/package/@pocesar/moip2))

**Comment by brunoosilva** [comment]
Pessoal criei essa versão para Nodejs, talvez ajude. Infelizmente essa versão atual está usando **window/navigator/etc**... coisas que não rola no Node, basicamente é o mesmo código e testes.

https://www.npmjs.com/package/moip-sdk-js

@pocesar Muito bom a sua versão hein, vou usar no meu app React Native =D

**Comment by deyvidfk** [comment]
Vejo a comunidade criando inúmeros repositórios NPM como um  wrap's da API oficial com o intuito de colabora, isso é muito legal porem particularmente eu me sentiria mais seguro obtendo a versão da conta oficial da MOIP.

**Comment by somentelucas** [comment]
Pessoal, demorou mas deu certo! ❤️ 

Nós oficializamos o repositório que o @brunoosilva desenvolveu e agora ela é nossa SDK oficial de criptografia JS: https://github.com/moip/moip-sdk-js

Grande agradecimento à sua contribuição, @brunoosilva
